# Generated by Django 3.1.7 on 2021-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210716_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('d', 'فعال'), ('p', 'غیر فعال')], default=None, max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
