# Generated by Django 3.1.7 on 2021-07-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='statuss',
        ),
    ]
