# Generated by Django 3.1.7 on 2021-03-28 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام برند')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('slug', models.SlugField(max_length=200, verbose_name='آدرس برن')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('blue', 'آبی'), ('yellow', 'زرد'), ('green', 'سبز'), ('black', 'سیاه'), ('gray', 'خاکستری'), ('white', 'سفید')], max_length=10, verbose_name='رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='دسته بندی کالا')),
                ('slug', models.SlugField(max_length=200, verbose_name='آدرس  دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا ')),
                ('position', models.IntegerField(verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SizeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, verbose_name='سایز')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کالا')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('slug', models.SlugField(max_length=200, verbose_name='آدرس محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.brand', verbose_name='برند')),
                ('color', models.ManyToManyField(related_name='product', to='Product.Color', verbose_name='صفات ویژه')),
                ('productcategory', models.ManyToManyField(related_name='product', to='Product.ProductCategory', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-publish'],
            },
        ),
        migrations.AddField(
            model_name='color',
            name='sizecount',
            field=models.ManyToManyField(related_name='color', to='Product.SizeCount', verbose_name='صفات ویژه'),
        ),
    ]
