# Generated by Django 3.1.7 on 2021-04-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('Product', '0003_auto_20210412_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcategory',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='Product.product', verbose_name='صفات ویژه'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='blog.Category', verbose_name='دسته بندی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images', verbose_name='عکس'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
