# Generated by Django 3.1.7 on 2021-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210413_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialfield',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'قرمز'), ('blue', 'آبی'), ('yellow', 'زرد'), ('green', 'سبز'), ('black', 'سیاه'), ('gray', 'خاکستری'), ('white', 'سفید')], default=None, max_length=10, verbose_name='رنگ'),
        ),
    ]
