# Generated by Django 3.1.7 on 2021-04-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210413_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeshose',
            name='name',
            field=models.CharField(default=None, max_length=8, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spesial', to='Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='sizePants',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizePants', to='Product.sizepants', verbose_name='سایز شلوار'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='sizeShirt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShirt', to='Product.sizeshirt', verbose_name='سایز پیراهن'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='sizeShose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShose', to='Product.sizeshose', verbose_name='سایز کفش'),
        ),
    ]
