# Generated by Django 3.1.7 on 2021-04-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210417_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeshose',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='sizePants',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizePants', to='Product.sizepants', verbose_name='سایز شلوار'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeShirt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShirt', to='Product.sizeshirt', verbose_name='سایز پیراهن'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeShose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShose', to='Product.sizeshose', verbose_name='سایز کفش'),
        ),
        migrations.AddField(
            model_name='sizepants',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='sizeshirt',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='sizeshose',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.DeleteModel(
            name='SpecialField',
        ),
    ]
