# Generated by Django 3.1.7 on 2021-04-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210417_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizePants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShirt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShose',
        ),
        migrations.CreateModel(
            name='SpecialField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spesial', to='Product.product', verbose_name='محصول')),
                ('sizePants', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizePants', to='Product.sizepants', verbose_name='سایز شلوار')),
                ('sizeShirt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShirt', to='Product.sizeshirt', verbose_name='سایز پیراهن')),
                ('sizeShose', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeShose', to='Product.sizeshose', verbose_name='سایز کفش')),
            ],
        ),
    ]
