# Generated by Django 3.1.7 on 2021-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210417_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialfield',
            name='sizePants',
            field=models.ManyToManyField(default=None, related_name='sizePants', to='Product.SizePants', verbose_name='سایز شلوار'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='sizeShirt',
            field=models.ManyToManyField(default=None, related_name='sizeShirt', to='Product.SizeShirt', verbose_name='سایز پیراهن'),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='sizeShose',
            field=models.ManyToManyField(default=None, related_name='sizeShose', to='Product.SizeShose', verbose_name='سایز کفش'),
        ),
    ]
