# Generated by Django 3.1.7 on 2021-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20210417_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizePants',
        ),
        migrations.AddField(
            model_name='product',
            name='sizePants',
            field=models.ManyToManyField(default=None, related_name='sizePants', to='Product.SizePants', verbose_name='سایز شلوار'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShirt',
        ),
        migrations.AddField(
            model_name='product',
            name='sizeShirt',
            field=models.ManyToManyField(default=None, related_name='sizeShirt', to='Product.SizeShirt', verbose_name='سایز پیراهن'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShose',
        ),
        migrations.AddField(
            model_name='product',
            name='sizeShose',
            field=models.ManyToManyField(default=None, related_name='sizeShose', to='Product.SizeShose', verbose_name='سایز کفش'),
        ),
    ]
