# Generated by Django 3.1.7 on 2021-04-18 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0014_auto_20210417_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizePants',
            field=models.ManyToManyField(blank=True, default=None, related_name='sizePants', to='Product.SizePants', verbose_name='سایز شلوار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeShirt',
            field=models.ManyToManyField(blank=True, default=None, related_name='sizeShirt', to='Product.SizeShirt', verbose_name='سایز پیراهن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeShose',
            field=models.ManyToManyField(blank=True, default=None, related_name='sizeShose', to='Product.SizeShose', verbose_name='سایز کفش'),
        ),
    ]
