# Generated by Django 3.1.7 on 2021-04-21 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0019_product_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizePants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShirt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeShose',
        ),
        migrations.AddField(
            model_name='sizepants',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_pants', to='Product.Product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='sizeshirt',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_shirt', to='Product.Product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='sizeshose',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_shose', to='Product.Product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
    ]
