# Generated by Django 3.1.7 on 2021-04-27 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0020_auto_20210421_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizepants', models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, verbose_name='سایز')),
                ('sizeshose', models.CharField(choices=[('32', '۳۲'), ('33', '۳۳'), ('34', '۳۴'), ('35', '۳۵'), ('36', '۳۶'), ('37', '۳۷'), ('38', '۳۸'), ('39', '۳۹'), ('40', '۴۰'), ('41', '۴۱'), ('42', '۴۲'), ('43', '۴۳'), ('44', '۴۴'), ('45', '۴۵'), ('46', '۴۶')], max_length=4, verbose_name='سایز')),
                ('sizeshirt', models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, verbose_name='سایز')),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('blue', 'آبی'), ('yellow', 'زرد'), ('green', 'سبز'), ('black', 'سیاه'), ('gray', 'خاکستری'), ('white', 'سفید')], default=None, max_length=10, verbose_name='رنگ')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
            ],
        ),
        migrations.RemoveField(
            model_name='sizeshirt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sizeshose',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_product', to=settings.AUTH_USER_MODEL, verbose_name='محصولات مورد علاقه ی شما'),
        ),
        migrations.DeleteModel(
            name='SizePants',
        ),
        migrations.DeleteModel(
            name='SizeShirt',
        ),
        migrations.DeleteModel(
            name='SizeShose',
        ),
        migrations.AddField(
            model_name='special',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_shirt', to='Product.Product', verbose_name='محصولات'),
        ),
    ]
