# Generated by Django 3.1.7 on 2021-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_auto_20210427_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('shose', 'کفش'), ('pants', 'شلوار'), ('shirt', 'پیراهن'), ('headgear', 'روسری'), ('manto', 'مانتو')], default=None, max_length=10, verbose_name='نوع محصول'),
        ),
    ]
