# Generated by Django 3.1.7 on 2021-05-31 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210427_1347'),
        ('Product', '0023_auto_20210509_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='special',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductSpecialRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(related_name='product', to='blog.Category', verbose_name='دسته بندی محصول')),
                ('favourite', models.ManyToManyField(blank=True, default=None, related_name='favourite_product', to=settings.AUTH_USER_MODEL, verbose_name='محصولات مورد علاقه ی شما')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rel', to='Product.product', verbose_name='محصولات')),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='gallery', verbose_name='عکس')),
                ('product_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productspecialrelation', verbose_name='محصولات')),
            ],
        ),
        migrations.AddField(
            model_name='special',
            name='special',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_rel', to='Product.productspecialrelation', verbose_name='محصولات'),
        ),
    ]
