# Generated by Django 3.1.7 on 2021-08-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0028_brand_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='seller_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seller_2', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
    ]
