# Generated by Django 3.1.7 on 2021-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_special_seller_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('kid', 'کودک')], default=None, max_length=7, verbose_name='جنسیت'),
        ),
    ]
