# Generated by Django 3.1.7 on 2021-12-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='special',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='special',
            name='sizepants',
            field=models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, unique=True, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='special',
            name='sizeshirt',
            field=models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, unique=True, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='special',
            name='sizeshose',
            field=models.CharField(choices=[('32', '۳۲'), ('33', '۳۳'), ('34', '۳۴'), ('35', '۳۵'), ('36', '۳۶'), ('37', '۳۷'), ('38', '۳۸'), ('39', '۳۹'), ('40', '۴۰'), ('41', '۴۱'), ('42', '۴۲'), ('43', '۴۳'), ('44', '۴۴'), ('45', '۴۵'), ('46', '۴۶')], max_length=4, unique=True, verbose_name='سایز'),
        ),
    ]
