# Generated by Django 3.1.7 on 2021-12-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_auto_20211203_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='sizepants',
            field=models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='special',
            name='sizeshirt',
            field=models.CharField(choices=[('m', 'مدیوم'), ('l', 'لارج'), ('xl', 'ایکس لارج'), ('xxl', 'دو ایکس لارج'), ('xxxl', 'سه ایکس لارج')], max_length=4, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='special',
            name='sizeshose',
            field=models.CharField(choices=[('32', '۳۲'), ('33', '۳۳'), ('34', '۳۴'), ('35', '۳۵'), ('36', '۳۶'), ('37', '۳۷'), ('38', '۳۸'), ('39', '۳۹'), ('40', '۴۰'), ('41', '۴۱'), ('42', '۴۲'), ('43', '۴۳'), ('44', '۴۴'), ('45', '۴۵'), ('46', '۴۶')], max_length=4, verbose_name='سایز'),
        ),
    ]
