# Generated by Django 3.1.7 on 2021-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_auto_20211204_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images', verbose_name='عکس'),
        ),
    ]
