# Generated by Django 3.1.7 on 2021-04-21 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
